language: node_js

node_js:
  - '10'

addons:
  ssh_known_hosts: 106.53.64.5

before_install:
  - openssl aes-256-cbc -K $encrypted_f097bdbd50c7_key -iv $encrypted_f097bdbd50c7_iv
    -in deploy_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 106.53.64.5\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
  - npm i
  - npm run build:static
  - npm run build:server
deploy:
  only:
    - prod
after_success:
  - ssh eago@106.53.64.5 'cd ~/ && git pull'
